### ISSUE TITLE
Consider mixing Tokio & Rayon

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/light-speed-io#25]
This idea is _very_ early! Right now, I only have a very fuzzy grasp of what I'm trying to achieve, and a fuzzy grasp of how that might be implemented! I'll use this issue to collect links and ideas.

## Background and context

At first glance, Tokio should be used for async IO (like building a web server). And Rayon should be used for running CPU-intensive tasks in parallel. The issue is that `light-speed-io` wants to do _both_ those tasks: loading data from huge numbers of files using non-blocking IO (using `io_uring` on Linux), and _also_ doing lots of CPU-intensive processing on those files (like decompressing in parallel).

## The use-case that motivates me to think again about using Tokio with Rayon

Jacob described a use-case, which I summarised in #24. The basic idea is: say we have millions of small files, and we want to combine these files to create a "re-chunked" version of this dataset on disk. In Jacob's example, there are 146,000 GRIB2 files per NWP init time, and all these files need to be saved into a handful of Zarr chunks. Each GRIB2 file has to be decompressed; and then the decompressed files have to be combined and sliced up again, and then those slices are compressed and saved back to disk.

## The broad shape of a possible solution

- change LSIO's API so that users can _group_ IO operations together. For the GRIB2 example, users would say to LSIO: "Group1 consists of the 146,000 GRIB files that must be combined into a handful of Zarr chunks. Group2 consists of the _next_ 146,000 GRIB files.".
- Users can optionally provide a `map` function to be applied (in parallel) to each GRIB2 file (to decompress it)
- Users provide a `reduce_group` function which receives all the GRIB buffers in that group. This outputs a vector of buffers (and paths and byte_ranges).
- Users can provide another `map` function that'll be applied in parallel to these buffers (to compress them).
- The compressed buffers are written to storage. The output storage system might be different to the input storage system. For example, we might be reading GRIB files from a cloud storage bucket, and writing Zarr chunks to a local SSD.

## How Rust async might help

Hopefully users could write code like:

**UPDATE**: I need to learn more about Rust's [Streams](https://tokio.rs/tokio/tutorial/streams) (async iterators).

```rust
// LSIO will create a thread which owns an io_uring instance, and keeps the SQ topped up.
// LSIO will read group_1 before starting to read group_2.
// `read_groups` will return an Stream of Streams (!).
let groups =  reader.read_groups([group_1_filenames, group_2_filenames]);

for group in groups {
    // Concurrently decompress items in group
    let handles = Vec::with_capacity(group.len());
    for item in group {
        let handle = tokio::spawn(async move {
            item.buffer = decompress_async(item.buffer).await;
            item
        };
        handles.push(handle);
    }

    // Wait for all buffers to be decompressed.
    // (I'm not sure if this is valid Rust!)
    let items = handles.iter().map(|handle| handle.await.unwrap()).collect();

    // Reduce all items in this group:
    let combined_items = combine_async(items).await;

    for item in combined_items {
        tokio::spawn(async move {
            let item.buffer = compress_async(item.buffer).await;
            // TODO: Use Sink to write data:
            writer.submit_write(item).await;
        };
     }
}

// Adapted from https://ryhl.io/blog/async-what-is-blocking/#the-rayon-crate
async fn decompress_async(buffer: [u8]) -> [u8] {
    let (send, recv) = tokio::sync::oneshot::channel();

    // Spawn a task on rayon.
    rayon::spawn(move || {
        // Perform an expensive computation.
        let decompressed_buffer = decompress(buffer)
        // Send the result back to Tokio.
        let _ = send.send(decompressed_buffer);
    });

    // Wait for the rayon task.
    recv.await.expect("Panic in rayon::spawn")
}
```

### Tutorials / blog posts

- Alice Ryhl's December 2020 blog post ["Async: What is blocking?"](https://ryhl.io/blog/async-what-is-blocking/). Gives a great example of how to use Rayon with Tokio. I shouldn't use Tokio's `spawn_blocking`. `spawn_blocking` is best suited for wrapping blocking IO, not for CPU-intensive tasks. Instead, use `rayon::spawn` with `tokio::sync::oneshot` (see Alice's blog for more details).

### Rust crates & PRs

- Rayon draft PR: [[WIP] Add the ability to spawn futures](https://github.com/rayon-rs/rayon/pull/679). Very relevant discussion. But the discussion largely halted in 2020 (with the PR still in "draft").
- Rayon issue: ["Using [Rayon's] ThreadPool for blocking I/O?"](https://github.com/rayon-rs/rayon/issues/779). Conclusion: Don't wait on blocking IO in a Rayon task, because that blocks that thread from participating in other Rayon tasks.
- [`tokio-rayon`](https://lib.rs/crates/tokio-rayon): "Mix async code with CPU-heavy thread pools using Tokio + Rayon". Last release was in 2021.
- The [`futures`](https://docs.rs/futures/latest/futures/index.html) crate. Contains `Streams` (which LSIO could use as the _source_ of data. `Streams` are async iterators.), and `Sinks` (for writing data).
- [`async_stream`](https://docs.rs/async-stream/0.3.5/async_stream/#) "Provides two macros, `stream!` and `try_stream!`, allowing the caller to define asynchronous streams of elements. These are implemented using `async` & `await` notation." Allows us to define streams using a very similar approach to Python, using `yield`. Also allows us to write `for await value in input` to implement one stream from another stream.

**Comment by JackKelly** [comment]
## Can I use _only_ Rayon? 

Am I _sure_ we need `tokio`? If we're gonna ask users to write as much code as is in the snippet above, would it be better to just use Rayon? Maybe the "dream" with `tokio` is that users can avoid writing all the code above, and can instead write code like `read().map(|buf| decompress(buf)).collect_group().map(|buf| compress(buf)).for_each(|buf| write(buf))` using `Stream`s and `Sink`s? Either way, I should continue learning about `tokio`, `Stream`s and `Sink`s.

**Comment by JackKelly** [comment]
(@jacobbieker the conversation we had on Wednesday morning about needing to handle use-cases like your ICON GRIB-to-Zarr use-case has pushed me to completely reconsider the API and internal design for `light-speed-io`! Which is great! I'm optimistic that this new API will be much more flexible... as well as being much simpler!)

**Comment by jacobbieker** [comment]
Glad it helped! Very excited to see how this progresses!

**Comment by JackKelly** [comment]
Some relevant links:

* https://www.reddit.com/r/rust/comments/11ysnvz/the_asynciterator_interface/ - includes the point that `AsyncInterator` is the same as `Stream`.
* https://users.rust-lang.org/t/async-iterator-aka-stream-which-crate-to-use/65776 - good discussion of which crate to use, and how to actually implement a `Stream`

**Comment by JackKelly** [comment]
Oh, wait, AsyncIterator already has a from_iter method! https://docs.rs/async-iterator/latest/async_iterator/trait.FromIterator.html

Although I need to think how to keep the submission queue topped up, within the async iterator.

**Comment by JackKelly** [comment]
My plan is now for LSIO to "just" focus on async IO. So LSIO won't contain any `Rayon` code. And to have a separate crate for _processing_ `Stream`s in parallel (#26) using Rayon.

See https://github.com/JackKelly/light-speed-io/milestone/1
